In [19]:
import pandas as pd
import numpy as np
from pathlib import Path

In [20]:
csvpath = Path('../Project-03/combined_df.csv')
df = pd.read_csv(csvpath)

In [21]:
df.head()

,Unnamed: 0,H_TEAM,H_TEAM1,H_H/A,H_TEAM2,GAMEDATE,H_W/L,H_MIN,H_PTS,H_FGM,...,A_FT%,A_OREB,A_DREB,A_REB,A_AST,A_TOV,A_STL,A_BLK,A_PF,A_+/-
0,0,ATL,ATL,vs,SAS,2021-04-18,W,53,114,42,...,86.4,9,38,47,27,12,5,6,21,-2
1,1,ATL,ATL,vs,GSW,2021-04-18,L,48,100,37,...,68.0,13,34,47,30,21,15,7,17,1
2,2,ATL,ATL,vs,IND,2021-04-18,W,48,116,42,...,82.9,13,26,39,24,11,8,4,24,-5
3,3,ATL,ATL,vs,MIA,2021-04-18,L,63,109,36,...,78.3,14,42,56,25,22,6,6,35,7
4,4,ATL,ATL,vs,BOS,2021-04-18,L,48,81,28,...,66.7,16,28,44,27,13,11,4,15,8

In [22]:
df.info('include=all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12738 entries, 0 to 12737
Data columns (total 53 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  12738 non-null  int64
 1   H_TEAM      12738 non-null  object
 2   H_TEAM1     12738 non-null  object
 3   H_H/A       12738 non-null  object
 4   H_TEAM2     12738 non-null  object
 5   GAMEDATE    12738 non-null  object
 6   H_W/L       12738 non-null  object
 7   H_MIN       12738 non-null  int64
 8   H_PTS       12738 non-null  int64
 9   H_FGM       12738 non-null  int64
 10  H_FGA       12738 non-null  int64
 11  H_FG%       12738 non-null  float64
 12  H_3PM       12738 non-null  int64
 13  H_3PA       12738 non-null  int64
 14  H_3P%       12738 non-null  float64
 15  H_FTM       12738 non-null  int64
 16  H_FTA       12738 non-null  int64
 17  H_FT%       12738 non-null  float64
 18  H_OREB      12738 non-null  int64
 19  H_DREB      12738 non-null  int64
 20  H_REB       12738 non-null  int64
 21  H_AST       12738 non-null  int64
 22  H_TOV       12738 non-null  int64
 23  H_STL       12738 non-null  int64
 24  H_BLK       12738 non-null  int64
 25  H_PF        12738 non-null  int64
 26  H_+/-       12738 non-null  int64
 27  A_TEAM      12738 non-null  object
 28  A_TEAM1     12738 non-null  object
 29  A_H/A       12738 non-null  object
 30  A_TEAM2     12738 non-null  object
 31  GAMEDATE.1  12738 non-null  object
 32  A_W/L       12738 non-null  object
 33  A_MIN       12738 non-null  int64
 34  A_PTS       12738 non-null  int64
 35  A_FGM       12738 non-null  int64
 36  A_FGA       12738 non-null  int64
 37  A_FG%       12738 non-null  float64
 38  A_3PM       12738 non-null  int64
 39  A_3PA       12738 non-null  int64
 40  A_3P%       12738 non-null  float64
 41  A_FTM       12738 non-null  int64
 42  A_FTA       12738 non-null  int64
 43  A_FT%       12738 non-null  float64
 44  A_OREB      12738 non-null  int64
 45  A_DREB      12738 non-null  int64
 46  A_REB       12738 non-null  int64
 47  A_AST       12738 non-null  int64
 48  A_TOV       12738 non-null  int64
 49  A_STL       12738 non-null  int64
 50  A_BLK       12738 non-null  int64
 51  A_PF        12738 non-null  int64
 52  A_+/-       12738 non-null  int64
dtypes: float64(6), int64(35), object(12)
memory usage: 5.2+ MB

In [23]:
df = df.drop(columns=['Unnamed: 0'])

In [24]:
# dropping columns for model tuning

df = df.drop(columns=['A_H/A',
                      'H_+/-',
                      'A_+/-',
                      'H_PTS',
                      'A_PTS',
                      'A_W/L',
                      'H_FGM',
                      'A_FGM',
                      'H_REB',
                      'A_REB',
                      'H_FTM',
                      'A_FTM',
                      'H_FTA',
                      'A_FTA',
                      'H_TEAM',
                      'A_TEAM',
                      'GAMEDATE.1'])

In [25]:
df.info('include=all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12738 entries, 0 to 12737
Data columns (total 35 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   H_TEAM1   12738 non-null  object
 1   H_H/A     12738 non-null  object
 2   H_TEAM2   12738 non-null  object
 3   GAMEDATE  12738 non-null  object
 4   H_W/L     12738 non-null  object
 5   H_MIN     12738 non-null  int64
 6   H_FGA     12738 non-null  int64
 7   H_FG%     12738 non-null  float64
 8   H_3PM     12738 non-null  int64
 9   H_3PA     12738 non-null  int64
 10  H_3P%     12738 non-null  float64
 11  H_FT%     12738 non-null  float64
 12  H_OREB    12738 non-null  int64
 13  H_DREB    12738 non-null  int64
 14  H_AST     12738 non-null  int64
 15  H_TOV     12738 non-null  int64
 16  H_STL     12738 non-null  int64
 17  H_BLK     12738 non-null  int64
 18  H_PF      12738 non-null  int64
 19  A_TEAM1   12738 non-null  object
 20  A_TEAM2   12738 non-null  object
 21  A_MIN     12738 non-null  int64
 22  A_FGA     12738 non-null  int64
 23  A_FG%     12738 non-null  float64
 24  A_3PM     12738 non-null  int64
 25  A_3PA     12738 non-null  int64
 26  A_3P%     12738 non-null  float64
 27  A_FT%     12738 non-null  float64
 28  A_OREB    12738 non-null  int64
 29  A_DREB    12738 non-null  int64
 30  A_AST     12738 non-null  int64
 31  A_TOV     12738 non-null  int64
 32  A_STL     12738 non-null  int64
 33  A_BLK     12738 non-null  int64
 34  A_PF      12738 non-null  int64
dtypes: float64(6), int64(22), object(7)
memory usage: 3.4+ MB

In [26]:
df['GAMEDATE'] = pd.to_datetime(df['GAMEDATE'])

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12738 entries, 0 to 12737
Data columns (total 35 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   H_TEAM1   12738 non-null  object
 1   H_H/A     12738 non-null  object
 2   H_TEAM2   12738 non-null  object
 3   GAMEDATE  12738 non-null  datetime64[ns]
 4   H_W/L     12738 non-null  object
 5   H_MIN     12738 non-null  int64
 6   H_FGA     12738 non-null  int64
 7   H_FG%     12738 non-null  float64
 8   H_3PM     12738 non-null  int64
 9   H_3PA     12738 non-null  int64
 10  H_3P%     12738 non-null  float64
 11  H_FT%     12738 non-null  float64
 12  H_OREB    12738 non-null  int64
 13  H_DREB    12738 non-null  int64
 14  H_AST     12738 non-null  int64
 15  H_TOV     12738 non-null  int64
 16  H_STL     12738 non-null  int64
 17  H_BLK     12738 non-null  int64
 18  H_PF      12738 non-null  int64
 19  A_TEAM1   12738 non-null  object
 20  A_TEAM2   12738 non-null  object
 21  A_MIN     12738 non-null  int64
 22  A_FGA     12738 non-null  int64
 23  A_FG%     12738 non-null  float64
 24  A_3PM     12738 non-null  int64
 25  A_3PA     12738 non-null  int64
 26  A_3P%     12738 non-null  float64
 27  A_FT%     12738 non-null  float64
 28  A_OREB    12738 non-null  int64
 29  A_DREB    12738 non-null  int64
 30  A_AST     12738 non-null  int64
 31  A_TOV     12738 non-null  int64
 32  A_STL     12738 non-null  int64
 33  A_BLK     12738 non-null  int64
 34  A_PF      12738 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(22), object(6)
memory usage: 3.4+ MB

In [28]:
df.head(100)

,H_TEAM1,H_H/A,H_TEAM2,GAMEDATE,H_W/L,H_MIN,H_FGA,H_FG%,H_3PM,H_3PA,...,A_3PA,A_3P%,A_FT%,A_OREB,A_DREB,A_AST,A_TOV,A_STL,A_BLK,A_PF
0,ATL,vs,SAS,2021-04-18,W,53,92,45.7,14,28,...,27,33.3,86.4,9,38,27,12,5,6,21
1,ATL,vs,GSW,2021-04-18,L,48,80,46.3,10,31,...,27,22.2,68.0,13,34,30,21,15,7,17
2,ATL,vs,IND,2021-04-18,W,48,82,51.2,10,32,...,27,37.0,82.9,13,26,24,11,8,4,24
3,ATL,vs,MIA,2021-04-18,L,63,94,38.3,6,22,...,28,28.6,78.3,14,42,25,22,6,6,35
4,ATL,vs,BOS,2021-04-18,L,48,68,41.2,10,29,...,16,18.8,66.7,16,28,27,13,11,4,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ATL,vs,CHA,2021-04-13,L,48,86,53.5,14,33,...,42,45.2,77.8,10,27,30,14,12,7,17
96,ATL,vs,NYK,2021-04-12,W,58,108,45.4,14,40,...,34,38.2,72.0,15,41,30,18,12,6,29
97,ATL,vs,ORL,2021-04-12,L,48,80,46.3,13,32,...,37,35.1,89.3,11,38,29,8,4,9,21
98,ATL,vs,DET,2021-04-12,W,48,78,48.7,10,29,...,33,39.4,78.8,12,28,30,15,6,4,28
99,ATL,vs,CHA,2021-04-12,L,48,82,40.2,5,23,...,19,26.3,81.0,9,35,24,10,4,7,17

In [30]:
df['H_W/L']=df['H_W/L'].apply(lambda x: 1 if x=="W" else 0)

In [32]:
df.head(50)

,H_TEAM1,H_H/A,H_TEAM2,GAMEDATE,H_W/L,H_MIN,H_FGA,H_FG%,H_3PM,H_3PA,...,A_3PA,A_3P%,A_FT%,A_OREB,A_DREB,A_AST,A_TOV,A_STL,A_BLK,A_PF
0,ATL,vs,SAS,2021-04-18,1,53,92,45.7,14,28,...,27,33.3,86.4,9,38,27,12,5,6,21
1,ATL,vs,GSW,2021-04-18,0,48,80,46.3,10,31,...,27,22.2,68.0,13,34,30,21,15,7,17
2,ATL,vs,IND,2021-04-18,1,48,82,51.2,10,32,...,27,37.0,82.9,13,26,24,11,8,4,24
3,ATL,vs,MIA,2021-04-18,0,63,94,38.3,6,22,...,28,28.6,78.3,14,42,25,22,6,6,35
4,ATL,vs,BOS,2021-04-18,0,48,68,41.2,10,29,...,16,18.8,66.7,16,28,27,13,11,4,15
5,ATL,vs,NYK,2021-04-18,0,48,87,42.5,15,39,...,18,27.8,91.7,11,35,20,9,7,6,20
6,ATL,vs,MIA,2021-04-18,1,48,91,47.3,10,24,...,34,14.7,55.6,12,29,23,14,11,7,17
7,ATL,vs,DEN,2021-04-18,0,48,77,45.5,18,39,...,27,33.3,74.1,7,34,27,4,4,6,23
8,ATL,vs,CHI,2021-04-18,1,48,83,56.6,9,12,...,14,42.9,80.0,17,26,21,20,8,5,9
9,ATL,vs,MEM,2021-04-18,1,48,72,44.4,13,25,...,17,29.4,100.0,8,31,20,21,10,4,21
10,ATL,vs,IND,2021-04-18,1,48,84,42.9,11,22,...,17,29.4,87.0,11,32,17,15,4,5,22
11,ATL,vs,IND,2021-04-18,1,48,75,45.3,10,23,...,27,33.3,88.9,14,32,19,20,7,4,21
12,ATL,vs,HOU,2021-04-18,0,48,106,36.8,13,44,...,45,28.9,75.6,16,43,22,13,7,7,21
13,ATL,vs,CHI,2021-04-18,1,48,94,52.1,10,24,...,18,38.9,83.9,12,34,16,22,7,6,13
14,ATL,vs,HOU,2021-04-18,1,48,86,37.2,9,32,...,19,31.6,72.7,10,34,15,18,3,2,18
15,ATL,vs,UTA,2021-04-18,1,48,72,55.6,9,19,...,20,40.0,78.9,7,28,29,17,9,4,22
16,ATL,vs,WAS,2021-04-17,1,48,89,47.2,16,31,...,20,25.0,80.0,8,31,25,20,5,7,16
17,ATL,vs,CHA,2021-04-17,1,48,90,46.7,6,19,...,8,12.5,87.5,4,26,21,12,3,6,19
18,ATL,vs,BKN,2021-04-17,0,48,80,46.3,11,28,...,34,38.2,65.4,13,30,29,15,8,1,24
19,ATL,vs,BOS,2021-04-17,0,48,84,42.9,11,30,...,44,38.6,73.7,9,34,22,12,7,3,16
20,ATL,vs,MIL,2021-04-17,0,48,96,40.6,12,38,...,30,36.7,72.7,8,31,28,14,13,4,25
21,ATL,vs,MIN,2021-04-17,1,48,78,41.0,7,21,...,21,19.0,91.7,10,30,21,15,12,4,21
22,ATL,vs,PHX,2021-04-17,1,48,93,49.5,14,31,...,20,20.0,81.3,10,30,20,12,9,6,19
23,ATL,vs,HOU,2021-04-17,0,48,87,49.4,10,26,...,20,35.0,100.0,11,34,24,13,7,2,16
24,ATL,vs,MIL,2021-04-17,1,48,80,52.5,13,26,...,19,31.6,77.8,13,23,25,17,11,4,25
25,ATL,vs,SAS,2021-04-17,1,48,86,46.5,9,25,...,22,36.4,85.0,8,29,24,9,12,5,13
26,ATL,vs,OKC,2021-04-17,1,48,90,62.2,18,37,...,32,28.1,75.6,15,25,22,12,16,3,18
27,ATL,vs,TOR,2021-04-17,1,48,71,45.1,5,13,...,12,25.0,68.2,11,31,19,17,4,6,27
28,ATL,vs,BKN,2021-04-16,1,48,78,57.7,8,21,...,26,15.4,100.0,18,19,17,14,9,2,19
29,ATL,vs,BKN,2021-04-16,0,48,81,49.4,8,25,...,27,59.3,71.4,12,28,38,19,7,4,21
30,ATL,vs,BKN,2021-04-16,1,48,79,55.7,8,29,...,20,30.0,63.2,7,29,22,17,5,3,17
31,ATL,vs,SAC,2021-04-16,1,48,83,47.0,5,20,...,9,11.1,68.2,17,30,18,8,6,3,17
32,ATL,vs,NOP,2021-04-16,1,48,89,41.6,10,40,...,27,37.0,68.4,9,34,27,14,5,6,20
33,ATL,vs,POR,2021-04-16,1,48,71,46.5,5,11,...,19,26.3,70.0,13,28,23,9,10,5,21
34,ATL,vs,ORL,2021-04-16,1,48,80,51.3,9,19,...,22,27.3,75.0,11,31,21,13,11,5,13
35,ATL,vs,DET,2021-04-16,0,48,93,43.0,10,34,...,32,46.9,76.0,11,30,31,18,12,8,18
36,ATL,vs,SAS,2021-04-16,0,48,85,41.2,8,21,...,24,33.3,72.7,5,34,21,9,8,4,15
37,ATL,vs,DET,2021-04-16,1,48,84,44.0,9,30,...,35,25.7,57.7,20,41,17,19,6,2,17
38,ATL,vs,BOS,2021-04-16,0,48,92,43.5,12,41,...,32,37.5,92.0,11,32,19,15,10,8,18
39,ATL,vs,MIA,2021-04-16,1,48,81,51.9,12,31,...,33,45.5,82.1,8,29,28,18,9,2,26
40,ATL,vs,CHI,2021-04-16,1,48,82,47.6,9,22,...,28,25.0,94.7,12,29,18,25,12,5,17
41,ATL,vs,CHI,2021-04-16,0,48,92,38.0,11,48,...,32,43.8,90.5,4,44,31,16,8,1,23
42,ATL,vs,TOR,2021-04-16,0,48,83,49.4,12,33,...,42,31.0,76.7,12,33,25,14,13,3,25
43,ATL,vs,NOH,2021-04-16,0,48,79,29.1,4,20,...,15,53.3,90.9,11,44,26,14,8,5,18
44,ATL,vs,CLE,2021-04-16,1,48,83,55.4,11,24,...,20,35.0,70.4,5,28,18,20,6,3,19
45,ATL,vs,MIN,2021-04-16,1,48,71,57.7,10,16,...,14,35.7,73.1,10,20,24,20,12,6,21
46,ATL,vs,IND,2021-04-16,1,48,78,50.0,13,29,...,25,20.0,92.3,10,32,22,18,7,2,21
47,ATL,vs,PHI,2021-04-16,1,48,91,49.5,7,20,...,29,41.4,83.3,7,32,27,22,8,6,19
48,ATL,vs,ORL,2021-04-16,0,48,86,45.3,9,30,...,29,37.9,90.5,9,36,29,11,8,8,22
49,ATL,vs,UTA,2021-04-16,1,48,83,48.2,12,26,...,15,26.7,71.4,7,32,20,17,8,6,15